"""添加城市创建者字段

Revision ID: 1f2d9671f786
Revises: 7e512469175d
Create Date: 2025-01-01 20:48:59.165022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2d9671f786'
down_revision = '7e512469175d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 获取第一个管理员用户的 ID
    connection = op.get_bind()
    admin_id = connection.execute(sa.text(
        'SELECT id FROM users WHERE email = :email'
    ), {'email': 'admin@example.com'}).scalar()
    
    if not admin_id:
        # 如果没有管理员用户，创建一个
        result = connection.execute(sa.text(
            'INSERT INTO users (username, email, password_hash, created_at, updated_at) '
            'VALUES (:username, :email, :password_hash, NOW(), NOW())'
        ), {
            'username': 'admin',
            'email': 'admin@example.com',
            'password_hash': 'pbkdf2:sha256:600000$xxx'
        })
        admin_id = result.lastrowid
    
    # 2. 更新所有城市的 creator_id
    connection.execute(sa.text(
        'UPDATE cities SET creator_id = :admin_id WHERE creator_id IS NULL'
    ), {'admin_id': admin_id})
    
    # 3. 添加外键约束
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
