"""初始化数据库

Revision ID: initial_migration
Revises: 
Create Date: 2025-01-01 20:57:21.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'initial_migration'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=64), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    
    op.create_table('cities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('code', sa.String(length=10), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('image_url', sa.String(length=256), nullable=True),
        sa.Column('weather', sa.String(length=64), nullable=True),
        sa.Column('livability_score', sa.Float(), nullable=True),
        sa.Column('suitable_crowd', sa.String(length=256), nullable=True),
        sa.Column('cost_of_living', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('housing_cost', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('has_high_speed_rail', sa.Boolean(), nullable=True),
        sa.Column('has_subway', sa.Boolean(), nullable=True),
        sa.Column('has_airport', sa.Boolean(), nullable=True),
        sa.Column('medical_score', sa.Float(), nullable=True),
        sa.Column('education_score', sa.Float(), nullable=True),
        sa.Column('life_score', sa.Float(), nullable=True),
        sa.Column('avg_house_price', sa.Integer(), nullable=True),
        sa.Column('house_types', sa.String(length=256), nullable=True),
        sa.Column('house_sizes', sa.String(length=256), nullable=True),
        sa.Column('house_price_range', sa.String(length=128), nullable=True),
        sa.Column('house_description', sa.Text(), nullable=True),
        sa.Column('creator_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_code'), 'cities', ['code'], unique=True)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=True)
    
    op.create_table('city_reviews',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('city_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('score', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city_reviews')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_code'), table_name='cities')
    op.drop_table('cities')
    op.drop_table('users')
    # ### end Alembic commands ###
